### ISSUE TITLE
Did not install Waydroid on OTA-24.

### ISSUE THREAD

**Issue by Talkless** [Aarontheissueguy/WaydroidHelper#22]
I was using Waydroid on OTA-23 on Volla Phone X.
I've uninstalled Waydroid, instsalled OTA-24 update, installed Waydroid again, but after reboot I see no Waydroid application icon, and `waydroid -help` says `command not found`.

Let me know how could I debug this.

**Comment by Talkless** [comment]
I do see `linage_halium_arm64-userdebug 10 QQ3A.200805.001` as a kernel.

**Comment by Talkless** [comment]
I've fixed this by:
```
sudo mount -o remount,rw /
sudo sed -i '/aidl/s/2/3/' /etc/gbinder.d/anbox.conf
```
Thanks to stanwood: https://forums.ubports.com/post/68921

**Comment by JamiKettunen** [comment]
> I've fixed this by:
> 
> ```
> sudo mount -o remount,rw /
> sudo sed -i '/aidl/s/2/3/' /etc/gbinder.d/anbox.conf
> ```

I have no idea how those fix a missing `waydroid` executable, but yes that is a known issue and will be solved with Waydroid package upgrades: https://ubports.atlassian.net/browse/YUMI-11

**Comment by Talkless** [comment]
> I have no idea how those fix a missing waydroid executable

I simply installed second time, and they appeared. For some reason first install after upgrade probably failed in some strange way.

**Comment by Talkless** [comment]
@JamiKettunen I probably should not have pasted this "fix" here. It's for the other issue, where you start Waydroid, but no UI appears, and keeps loading.

**Comment by Talkless** [comment]
@JamiKettunen 

>will be solved with Waydroid package upgrades

So at some point, we will have to simply reinstall Waydroid using WaydroidHelper to install latest version? Or new WaydroidHelper has to released _first_ and then Waydroid re-installed?

**Comment by JamiKettunen** [comment]
Nothing has to be reinstalled if you already have it working, but once the Ubuntu Touch packages for Waydroid are updated and available in the repo you don't need to mess with `/etc/gbinder.d/anbox.conf` or anything like that, so you could install it through Waydroid Helper again like previously maybe a month or so ago now.

**Comment by Talkless** [comment]
@JamiKettunen Maybe it's worth to implement some sort of check in WaydroidHelper to detect that newer Waydroid is available (if current Waydroid installed version is older than currently available in dpgk repository)? 

Simply running `apt policy waydroid` would probably be enough to figure it out I guess?

**Comment by JamiKettunen** [comment]
Since the original issue is fixed and no workaround should be needed anymore since `waydroid` v1.3.3 and `python3-gbinder` v1.1.1 are in UT 16.04 repos even on OTA-24 afaik so this issue can be closed.

As for your last message see #24 which should implement this by simply choosing "install" again.

**Comment by JamiKettunen** [comment]
You shouldn't need to worry about that as a user, but feel free to comment on the issue pull request I linked. The plan on 20.04 is to eventually bring Waydroid into the rootfs itself which would mean you don't have to install it manually or remount rootfs as read-write etc.

**Comment by Talkless** [comment]
> The plan on 20.04 is to eventually bring Waydroid into the rootfs itself

Oh, that's pretty cool. Thanks for info!

**Comment by JamiKettunen** [comment]
I think this issue can be re-opened and title changed to `Sometimes Waydroid doesn't install`, it sometimes works while other times not (maybe rebooting helps if this happens?). In my case it previously just got stuck on this screen (after I waited 30 minutes or so):
<img src="https://user-images.githubusercontent.com/47358222/207709701-f9781f56-4ed5-4544-8d78-caeb6ada13e8.png" width="240" />

I caught a `tail -f ~/.cache/upstart/application-click-waydroidhelper.aaronhafer_waydroidhelper_2.0.4.log` log from when it failed also on my end:
```
qml: installer module imported
[PERFORMANCE]: Last frame took 45 ms to render.
Starting bash and getting root privileges

"PyOtherSide error: Traceback (most recent call last):\n\n  File \"/opt/click.ubuntu.com/waydroidhelper.aaronhafer/2.0.4/src/installer.py\", line 24, in install\n    child.expect('root.*')\n\n  File \"deps/pexpect/spawnbase.py\", line 344, in expect\n    timeout, searchwindowsize, async_)\n\n  File \"deps/pexpect/spawnbase.py\", line 372, in expect_list\n    return exp.expect_loop(timeout)\n\n  File \"deps/pexpect/expect.py\", line 181, in expect_loop\n    return self.timeout(e)\n\n  File \"deps/pexpect/expect.py\", line 144, in timeout\n    raise exc\n\npexpect.exceptions.TIMEOUT: Timeout exceeded.\n<pexpect.pty_spawn.spawn object at 0x7f822f4240>\ncommand: /bin/bash\nargs: ['/bin/bash']\nbuffer (last 100 chars): b'\\r\\nSorry, try again.\\r\\n[sudo] password for phablet: '\nbefore (last 100 chars): b'\\r\\nSorry, try again.\\r\\n[sudo] password for phablet: '\nafter: <class 'pexpect.exceptions.TIMEOUT'>\nmatch: None\nmatch_index: None\nexitstatus: None\nflag_eof: False\npid: 6273\nchild_fd: 51\nclosed: False\ntimeout: 30\ndelimiter: <class 'pexpect.exceptions.EOF'>\nlogfile: None\nlogfile_read: None\nlogfile_send: None\nmaxread: 2000\nignorecase: False\nsearchwindowsize: None\ndelaybeforesend: 0.05\ndelayafterclose: 0.1\ndelayafterterminate: 0.1\nsearcher: searcher_re:\n    0: re.compile(b'root.*')\n"
qml: python error: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/opt/click.ubuntu.com/waydroidhelper.aaronhafer/2.0.4/src/installer.py", line 24, in install
    child.expect('root.*')

  File "deps/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)

  File "deps/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)

  File "deps/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)

  File "deps/pexpect/expect.py", line 144, in timeout
    raise exc

pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f822f4240>
command: /bin/bash
args: ['/bin/bash']
buffer (last 100 chars): b'\r\nSorry, try again.\r\n[sudo] password for phablet: '
before (last 100 chars): b'\r\nSorry, try again.\r\n[sudo] password for phablet: '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 6273
child_fd: 51
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'root.*')

qml: test was executed
```
Perhaps #14 might help with this, haven't tested it yet
