### ISSUE TITLE
Hiding first app on list (Android Keyboard (AOSP)) is broken

### ISSUE THREAD

**Issue by JamiKettunen** [Aarontheissueguy/WaydroidHelper#29]
```
Jan 30 17:05:44 ubuntu-phablet aa-exec[34835]: "PyOtherSide error: Traceback (most recent call last):\n\n  File \"/opt/click.ubuntu.com/waydroidhelper.aaronhafer/3.0.4/src/main.py\", line 71, in hide\n    abs_path = os.path.join(\"/home/phablet/.local/share/applications/\", path)\n\n  File \"/usr/lib/python3.8/posixpath.py\", line 90, in join\n    genericpath._check_arg_types('join', a, *p)\n\n  File \"/usr/lib/python3.8/genericpath.py\", line 152, in _check_arg_types\n    raise TypeError(f'{funcname}() argument must be str, bytes, or '\n\nTypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'\n"
Jan 30 17:05:44 ubuntu-phablet aa-exec[34835]: qml: python error: Return value of PyObject call is NULL: Traceback (most recent call last):
Jan 30 17:05:44 ubuntu-phablet aa-exec[34835]:   File "/opt/click.ubuntu.com/waydroidhelper.aaronhafer/3.0.4/src/main.py", line 71, in hide
Jan 30 17:05:44 ubuntu-phablet aa-exec[34835]:     abs_path = os.path.join("/home/phablet/.local/share/applications/", path)
Jan 30 17:05:44 ubuntu-phablet aa-exec[34835]:   File "/usr/lib/python3.8/posixpath.py", line 90, in join
Jan 30 17:05:44 ubuntu-phablet aa-exec[34835]:     genericpath._check_arg_types('join', a, *p)
Jan 30 17:05:44 ubuntu-phablet aa-exec[34835]:   File "/usr/lib/python3.8/genericpath.py", line 152, in _check_arg_types
Jan 30 17:05:44 ubuntu-phablet aa-exec[34835]:     raise TypeError(f'{funcname}() argument must be str, bytes, or '
Jan 30 17:05:44 ubuntu-phablet aa-exec[34835]: TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
Jan 30 17:05:44 ubuntu-phablet aa-exec[34835]: qml: hide was executed
```

**Comment by joaocandre** [comment]
Can confirm this issue (still) occurs.
